#
# Module manifest for module 'VSCodeExtensions'
#
# Generated by: Brandon Padgett
#
# Generated on: 6/28/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'VSCodeExtensions.psm1'

# Version number of this module.
ModuleVersion = '0.1.2'

# ID used to uniquely identify this module
GUID = '887a7425-6dbe-4150-966a-852d069832df'

# Author of this module
Author = 'Brandon Padgett'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2016 Brandon Padgett. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Module to Manage Visual Studio Code Extensions'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('Formats\ExtensionStats.format.ps1xml','Formats\PublisherStats.format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @('Find-VSCodeExtension','Get-VSCodeExtension','Get-VSCodeExtensionStats','Get-VSCodePublisherStats','Install-VSCodeExtension','Uninstall-VSCodeExtension','Update-VSCodeExtension')

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('vscode','extensions','Code','VS','VisualStudio','VisualStudioCode')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/gerane/VSCodeExtensions/blob/master/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/gerane/VSCodeExtensions'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @('# VSCodeExtensions Release History','','## 0.1.2','### 09/29/2016','!deploy','','Fixed Issue with metadata','- Added metadata to Extension Package.json files.','- Code stopped recognizing installed extensions if this metadata was missing. It should now detect they were installed from the marketplace.','','','','## 0.1.1','### 07/18/2016','Few Imporvements.','- appveyor: Added Slack notifications for builds','- Psake: Added Manifest auto updates','- FInd-VSCodeExtension: Added Installs and AssetUri properties to return','- Install-VSCodeExtension: Swapped to piping','- Formats: Moved formats to a format folder','- VSIX: moved from Extension object to properties and piping.','- Manifest: Added ReleaseNotes for PSGallery and Formats','- Tests: Added Manifest tests','','','## 0.1.0    ','### 7/17/2016','Imporved the handling of VSIX files.','Commands','- Find-VSCodeExtension','- Get-VSCodeExtension','- Get-VSCodeExtensionStats','- Get-VSCodePublisherStats','- Install-VSCodeExtension','- Uninstall-VSCodeExtension','- Update-VSCodeExtension','','','## 0.0.1','Initial Release')

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}























